### ISSUE TITLE
Segmentation fault in DeleteMagickThreadKey()

### ISSUE THREAD

**Issue by mariancerny** [mkoppanen/imagick#184]
We started using ImageMagick on one project and there are some segmentation faults I see from time to time, like this (request from apache):

```
(gdb) bt
#0  0x000000080ad18555 in DeleteMagickThreadKey () from /usr/local/lib/libMagickCore-6.so.2
#1  0x00000008235797d3 in UnregisterTIFFImage () from /usr/local/lib/ImageMagick-6.9.5/modules-Q16/coders/tiff.so
#2  0x000000080ac961f8 in LoadMimeLists () from /usr/local/lib/libMagickCore-6.so.2
#3  0x000000080ad07a88 in DestroySplayTree () from /usr/local/lib/libMagickCore-6.so.2
#4  0x000000080ac96e11 in DestroyModuleList () from /usr/local/lib/libMagickCore-6.so.2
#5  0x000000080ac96e43 in ModuleComponentTerminus () from /usr/local/lib/libMagickCore-6.so.2
#6  0x000000080ac91a5a in MagickCoreTerminus () from /usr/local/lib/libMagickCore-6.so.2
#7  0x000000080a677ce8 in zm_shutdown_imagick () from /usr/local/lib/php/20131226/imagick.so
#8  0x00000008056a9013 in module_destructor (module=0x802019b00) at /tmp/portbuild/usr/ports/www/mod_php56/work/php-5.6.27/Zend/zend_API.c:2421
#9  0x00000008056b1832 in zend_hash_bucket_delete (ht=0x805b11780, p=0x807014240) at /tmp/portbuild/usr/ports/www/mod_php56/work/php-5.6.27/Zend/zend_hash.c:182
#10 0x00000008056b1af8 in zend_hash_graceful_reverse_destroy (ht=0x805b11780) at /tmp/portbuild/usr/ports/www/mod_php56/work/php-5.6.27/Zend/zend_hash.c:613
#11 0x00000008056a49d2 in zend_shutdown () at /tmp/portbuild/usr/ports/www/mod_php56/work/php-5.6.27/Zend/zend.c:836
#12 0x000000080563ef55 in php_module_shutdown () at /tmp/portbuild/usr/ports/www/mod_php56/work/php-5.6.27/main/main.c:2477
#13 0x000000080563f009 in php_module_shutdown_wrapper (sapi_globals=<value optimized out>) at /tmp/portbuild/usr/ports/www/mod_php56/work/php-5.6.27/main/main.c:2445
#14 0x0000000805747161 in php_apache_child_shutdown (tmp=<value optimized out>) at /tmp/portbuild/usr/ports/www/mod_php56/work/php-5.6.27/sapi/apache2handler/sapi_apache2.c:398
#15 0x000000080161e30d in apr_pool_cleanup_run () from /usr/local/lib/libapr-1.so.0
#16 0x000000080161e979 in apr_pool_destroy () from /usr/local/lib/libapr-1.so.0
#17 0x000000000046f1ce in ap_set_etag ()
#18 0x000000000046f6c8 in ap_set_etag ()
#19 0x000000000046f9f0 in ap_set_etag ()
#20 0x000000000047030f in ap_set_etag ()
#21 0x0000000000437b92 in ap_run_mpm ()
#22 0x00000000004316e3 in main ()
```

Or this (php from command line):

```
(gdb) bt
#0  0x0000000806996555 in DeleteMagickThreadKey () from /usr/local/lib/libMagickCore-6.so.2
#1  0x000000081a9ab7d3 in UnregisterTIFFImage () from /usr/local/lib/ImageMagick-6.9.5/modules-Q16/coders/tiff.so
#2  0x00000008069141f8 in LoadMimeLists () from /usr/local/lib/libMagickCore-6.so.2
#3  0x0000000806985a88 in DestroySplayTree () from /usr/local/lib/libMagickCore-6.so.2
#4  0x0000000806914e11 in DestroyModuleList () from /usr/local/lib/libMagickCore-6.so.2
#5  0x0000000806914e43 in ModuleComponentTerminus () from /usr/local/lib/libMagickCore-6.so.2
#6  0x000000080690fa5a in MagickCoreTerminus () from /usr/local/lib/libMagickCore-6.so.2
#7  0x00000008062f5ce8 in zm_shutdown_imagick () from /usr/local/lib/php/20131226/imagick.so
#8  0x000000000057fbb5 in module_destructor (module=0x802588200) at /tmp/portbuild/usr/ports/lang/php56/work/php-5.6.27/Zend/zend_API.c:2421
#9  0x000000000058779f in zend_hash_bucket_delete (ht=0x9f5e00, p=0x80264b8d0) at /tmp/portbuild/usr/ports/lang/php56/work/php-5.6.27/Zend/zend_hash.c:182
#10 0x0000000000587a68 in zend_hash_graceful_reverse_destroy (ht=0x9f5e00) at /tmp/portbuild/usr/ports/lang/php56/work/php-5.6.27/Zend/zend_hash.c:613
#11 0x000000000057ae65 in zend_shutdown () at /tmp/portbuild/usr/ports/lang/php56/work/php-5.6.27/Zend/zend.c:836
#12 0x000000000051834a in php_module_shutdown () at /tmp/portbuild/usr/ports/lang/php56/work/php-5.6.27/main/main.c:2477
#13 0x000000000061b26c in main (argc=3, argv=0x7fffffffecd8) at /tmp/portbuild/usr/ports/lang/php56/work/php-5.6.27/sapi/cli/php_cli.c:1397
```

We are using the following environment:

```
FreeBSD 9.3-RELEASE-p42
amd64
php56-5.6.27
apache24-2.4.23_1
ImageMagick-nox11-6.9.5.10_1,1
pecl-imagick-3.4.1_1
tiff-4.0.6_2
```

**Comment by Danack** [comment]
Hmm. Seeing that from the command line is unusual.

Are you able to reproduce this reliably with a particular image and set of operations on that image, or is this a random thing?

**Comment by mariancerny** [comment]
I am not able to reproduce this easily. I am an admin and just examining core dumps when I see a notification in system logs. The developers don't know where it crashes. I plan to "fix" this issue by removing support for tiff from Image Magick.

**Comment by Danack** [comment]
The short version is that having a library that uses one implementation of threads, in an application that uses a different implementation of threads is very flaky. It's not something I recommend.

You can disable threading in ImageMagick by recompiling it without thread support, or by editing the file /etc/ImageMagick-6/policy.xml (or wherever it is on your system) to limit it to 1 thread:

```
<policy domain="resource" name="thread" value="1"/>
```

Just to be clear - I also don't recommend Imagick being used inside Apache. Running it from the command line and having your server transfer requests to process images to a background worker task is usually a lot more reliable, and slightly more secure.

**Comment by mariancerny** [comment]
Thanks for your advice. I have restricted the threading to one thread in policy.xml and will see how it goes next week.

**Comment by Danack** [comment]
I'm going to close this, as there's currently no action I can take on this issue.

Please post more information if you can find a reproducible problem.

**Comment by mariancerny** [comment]
I have disabled threads but that did not help.
I have removed support for tiff from ImageMagick and that helped.
